### ISSUE TITLE
Drag selector firing when dragging selected elements and the items get reset.

### ISSUE THREAD

**Issue by cercos** [ThibaultJanBeyer/DragSelect#144] opened 2022-11-02 22:41 UTC
**Describe the bug**
When I drag the selector and select items, the selector fires when I click on a selected item to drag it.

**To Reproduce**
1. Select items
2. Drag them
3. Selector tries to select new elements while dragging and resets items

**Expected behavior**
Selected items get ignored drag behavior

**Comment by owenfar** [comment] 2022-11-09 07:25
Hello @cercos, I was checking on this example provided by @ThibaultJanBeyer https://codepen.io/ThibaultJanBeyer/pen/bGKgVxp and I cannot reproduce.

If I understand correctly your issue, while dragging the selected items, a new DS is triggered and selects more items while dragging the original ones?

Have you solved it maybe? Or can you please try to reproduce it on something like codepen so that it is easier to understand the issue here please?

**Comment by cercos** [comment] 2022-11-10 00:05
@owenfar Yes.  That is exactly what is happening.  I will try to throw together a codepen or at least a gist by tomorrow.  I would do it right now just have a lot going on in life right now.

**Comment by ThibaultJanBeyer** [comment] 2023-03-05 13:14
Hey there, this issue has been open for a while, we could not reproduce it and we did not receive any codepen to reproduce. Closing it for now, feel free to re-open once you have a reproducible example. Thank you 👍

**Closed by ThibaultJanBeyer** 2023-03-05 13:14 UTC
Labels: awaiting feedback
