### ISSUE TITLE
I can't use Shift + click to add or remove new element into/from selected elements list like ctrl + click

### ISSUE THREAD

**Issue by addisu-abitew** [ThibaultJanBeyer/DragSelect#236] opened 2024-09-18 22:24 UTC
**Describe the bug**
Shift + click is not working to add or remove selection

**To Reproduce**
1. Select some elements
2. Click on one of the selectable elements while holding shift
4. See the behavior not selecting or removing selection from the clicked element

**Expected behavior**
It was expected to select or remove selection by default

**Comment by ThibaultJanBeyer** [comment] 2024-10-26 16:29
Hi there @addisu-abitew and welcome to DragSelect! Thanks a lot for trying the tool. I just checked this on https://dragselect.com/ and the `Shift + Click` works as expected.

I assume this issue is because of some custom code on your side, so I'll close this issue unless you are able to provide an example to reproduce the issue, feel free to [branch off from codepen](https://codepen.io/ThibaultJanBeyer/pen/YzvVYyR) or use any other tool. Thank you 🤗

**Closed by ThibaultJanBeyer** 2024-10-26 16:29 UTC
