### ISSUE TITLE
Difference in behavior between setSettings({selectables: [elements]}) and setSelectables([elements])?

### ISSUE THREAD

**Issue by justinross** [ThibaultJanBeyer/DragSelect#182] opened 2023-05-11 23:27 UTC
**Describe the bug**
This report might be entirely useless, but: implementing DragSelect in my vue app, I ran into a scenario where selectable elements weren't being added to my DragSelect instance with `ds.setSettings({selectables: [<elements>]})`, but *were* being added if I used `ds.setSelectables([<elements>])`. 

**To Reproduce**
I doubt there's a reasonable way to reproduce this. It's probably some Vue reactivity weirdness, as I can't even reproduce it in other parts of my app. It's just one specific section of my app, trying to add a bunch of `tr` elements. Other uses, with very similar code, work just fine with ds.setSettings(). 

**Expected behavior**
I expect

**Code Example**
For example, this:
```js
dragSelectInstance.stop();
console.log('Before setting', selectableElementArray);
dragSelectInstance.setSettings({
  area: areaElement,
  selectables: selectableElementArray,
  draggability: false,
});
console.log(
  'After setting',
  dragSelectInstance.getSelectables(),
  selectableElementArray
);
dragSelectInstance.start();
```
Gives this console.log output:
![image](https://github.com/ThibaultJanBeyer/DragSelect/assets/1120106/5bfd86dc-fb49-4ccd-bb3b-e3be76af9250)

While this code:
```js
dragSelectInstance.stop();
console.log('Before setting', selectableElementArray);
dragSelectInstance.setSettings({
  area: areaElement,
  draggability: false,
});
dragSelectInstance.setSelectables(selectableElementArray)
console.log(
  'After setting',
  dragSelectInstance.getSelectables(),
  selectableElementArray
);
```

Outputs this to the console (and works as expected):
![image](https://github.com/ThibaultJanBeyer/DragSelect/assets/1120106/285ae777-3b70-4f3b-abf6-450c0b8ea20e)

Given the deprecation warning, for now, I'll just manually remove all of the selectables from my instance, and add the new set. Just thought it was weird that setSettings and setSelectables would behave differently and that you might want to know, even if it's a weird niche case.

**Comment by ThibaultJanBeyer** [comment] 2023-06-03 19:13
Hi Justinross, thank you! This indeed is weird, especially because I wanted to remove the `setSelectables` as it in theory is supposed to do the same than `setSettings`. I’ll look into it 👀

**Comment by ThibaultJanBeyer** [comment] 2023-06-03 19:19
I believe this is because of the asynchronous nature of `setSettings`. When you `setSettings` what happens is that it dispatches an event that get then picked up by the various internal components. It could be that by logging them immediately after the event has not been yet picked up. I bet if you add a short delay between setting the settings and logging the values it would be correct.

Now how to solve that is a more complex question 🤔

**Comment by ThibaultJanBeyer** [comment] 2023-09-25 07:24
Closing as I could not reproduce. Feel free to re-open when you have a reproductive example. Thank you :)

**Closed by ThibaultJanBeyer** 2023-09-25 07:24 UTC
