### ISSUE TITLE
Prevent multi-selection on overlapped area of elements

### ISSUE THREAD

**Issue by Wenrong108** [ThibaultJanBeyer/DragSelect#107] opened 2021-07-29 08:40 UTC
**Describe the bug**
Hi, @ThibaultJanBeyer 
Thanks for releasing the great lib!
I have an issue. When I click overlapped area of elements, all overlapped elements are selected.
I want to select only a TOP element!
Hope your kind solution

Best Regards

**To Reproduce**
https://mochuan-video.tinytake.com/msc/NTY2OTEyM18xNzU1NTkyOA

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome
 - Version: v1.15.1

**Comment by ThibaultJanBeyer** [comment] 2021-08-22 06:25
Hi @Wenrong108 and thanks for using the tool.
This is super difficult as JavaScript has no concept of "first element" but I see the value so I'd like to know if more people would be interested in such a solution.
So I'll leave this open for vote, just add a thumb up 👍 if you'd like to have this.
Ofc. if someone is keen on adding it himself that would be a great addition, or if you have ideas on how to solve it, write them here :)

**Comment by owenfar** [comment] 2021-08-23 09:51
Hello everyone, I do think this should be in the pipeline eventually :)

Selecting by clicking on 1 item should only select that item, especially now with drag support.

If a user would like to select all elements at once they can use the normal dragSelect functionality.

@Wenrong108, for now you could try to implement a workaround using a callback function, and check if the topmost item in items is the same node, and disable the rest in the array - not sure if this is even possible, just a suggestion.

**Comment by ThibaultJanBeyer** [comment] 2021-08-23 09:55
Noted. And that's a good suggestion. Do you know if there is a way in JS to know that an element is the topmost element?

**Comment by owenfar** [comment] 2021-08-23 10:06
Did you implement this using elementsFromPoint() function? It depends on which method we're using the get the elements.

**Comment by ThibaultJanBeyer** [comment] 2021-08-23 14:43
> Did you implement this using elementsFromPoint() function? It depends on which method we're using the get the elements.

Oh! This is awesome. Sweet `elementsFromPoint` can be very useful here 🍰 🙇‍♀️

**Comment by ThibaultJanBeyer** [comment] 2021-12-24 19:54
@owenfar, @Wenrong108 is this still an issue? I just tested it on chrome and firefox with version v2.2.2 and could not reproduce it anymore. If I click, only the topmost element is selected.

I'll close it for now as solved. Please try to reproduce with the latest version if it's still the case for you.

Thank you! 🍄

**Closed by ThibaultJanBeyer** 2021-12-24 19:54 UTC
Labels: help wanted, up for vote
