### ISSUE TITLE
When scrolling is completed，the Selection Range is error

### ISSUE THREAD

**Issue by hezulong1** [ThibaultJanBeyer/DragSelect#231] opened 2024-08-28 05:38 UTC
**Describe the bug**

After **Area** scrolling is completed, the **Selection Range Error** problem will occur when you drag the left mouse button to select

**To Reproduce**
1. Click on the top of **Area**
2. Scroll down the **Area**
3. Left click and drag to select

**Expected behavior**
Draw the correct range.

**Code Example**
https://codepen.io/vividcat/pen/PorBqaq

**Screenshots**
![image](https://github.com/user-attachments/assets/03b5b609-66fc-4ec5-bb4c-f9e9f0ff7a37)

**Desktop (please complete the following information):**
 - OS: window10
 - Browser: chrome125
 - Version: DragSelect3.0.7

**Additional context**

**Comment by ThibaultJanBeyer** [comment] 2024-10-26 14:17
Hi @hezulong1 thanks a lot for using DragSelect 🫶 
Would you be so kind to past the error? Using your code example I am not able to reproduce the error.

What  I can see however is that the selection doesn't seem to be updated and always starts at the first place it was clicked 🤔👀

**Comment by ThibaultJanBeyer** [comment] 2024-10-26 16:45
Fixed in [Version 3.1.1](https://github.com/ThibaultJanBeyer/DragSelect/releases/tag/v3.1.1) have a nice weekend ✌️

**Closed by ThibaultJanBeyer** 2024-10-26 16:45 UTC
Labels: bug
