### ISSUE TITLE
Selection rectangle invisibly extends to top-left of screen when selecting SVG elements in Firefox >= v83

### ISSUE THREAD

**Issue by musicog** [ThibaultJanBeyer/DragSelect#82] opened 2021-03-22 12:55 UTC
**Describe the bug**
Working with SVGs of musical score, generated by [Verovio](https://verovio.org):
When clicking-and-dragging to select notes (i.e., "note"-class elements in the SVG), the browser correctly draws a matching selection rectangle; but the *actual* selection rectangle invisibly extends to the top-left corner of the screen. This means additional, non-intended elements are added into the selection. This problem only occurs on Firefox v83 and up; does not occur in Chrome, or in older versions of Firefox. 

**To Reproduce**
***JS FIDDLE EXAMPLE:*** **https://jsfiddle.net/b594wnys/1/**

1. Click and drag to select the first (left-most) two notes in the top staff
2. Click and drag again to select the last (right-most) few notes in the bottom staff

**Expected behavior**
In step 1, the first two notes are (correctly) selected.
In step 2, instead of the last few notes being selected as expected, all notes that fall into a rectangle drawn from the top-left corner of the screen to the cursor position (as its bottom-right corner) are selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/5521800/111991500-ae9c0780-8b14-11eb-8cf8-b1f266f7a3c0.png)
After step 1: User has dragged to select first two notes. Selection appears to have worked, because a rectangle drawn from the top-left corner of the screen to final cursor position (next to the second note) doesn't include any other notes.

![image](https://user-images.githubusercontent.com/5521800/111991783-f884ed80-8b14-11eb-964c-97936f60005e.png)
After step 2: User has dragged to select only the last (bottom-right) few notes, but all notes that fall within a rectangle drawn from the top-left corner of the screen to the final cursor position (next to the bottom-right-most note) are selected.

![image](https://user-images.githubusercontent.com/5521800/111992206-70ebae80-8b15-11eb-99ce-a21d912c258a.png)
Alternatively, here the user has dragged to select only a single note: the one directly above the "o" in legatissimo; but again, all notes in a rectangle drawn from the top-left corner of the screen to the final cursor position (next to that single note) are selected.

**Videos**
Firefox behaviour: 
https://drive.google.com/file/d/1xZ3e1mpET64DqdjIncB_2Mpl5QeyfRH9/view?usp=sharing

Chrome behavior: *please ignore the text selection, that's NOT the bug :-). Only look at the notes!*: 
https://drive.google.com/file/d/1S4eXgcop7ZPczFvAPRud63gpakdk2_cb/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Replicated on Fedora Linux v33, Mac OS X, Windows
 - Browser:  Only breaks in Firefox; works correctly in Chrome
 - Version: Replicated on v83 (Fedora Linux / Mac OS X), v86 (Windows). Didn't break in older versions.

**Comment by ThibaultJanBeyer** [comment] 2021-05-26 15:59
Hi @musicog and thank you for reporting this. I was not able to reproduce the issue you mentioned or at least I don't understand it even tho you made great efforts trying to explain it. It seems to be very edge-casy. 

How about google hangouts or something to walk over your issue in person?

**Comment by musicog** [comment] 2021-05-27 10:51
Hello @ThibaultJanBeyer - delighted to hear from you, and thanks for the very kind offer! It is an edge-case, but it's *my* edge-case :-). And affects a number of different music informatics research applications which have been built around our [selectable score](https://github.com/trompamusic/selectable-score) component, that all now have annoying Chrome requirements because of this issue.

Very happy to talk via Hangouts or anything else convenient to you. Please could you drop me an e-mail at `weigl at mdw.ac.at` and we can make arrangements. Thanks again!

**Comment by musicog** [comment] 2021-06-24 10:48
Hello @ThibaultJanBeyer, issue updated as per our discussion, including links to (animated gifs of) the videos - sorry, couldn't figure out how to include them natively in the issue!

I'll let you know how I do looking through the code - otherwise, your help when you have time would be greatly appreciated!

**Comment by ThibaultJanBeyer** [comment] 2021-08-22 07:30
Hi @musicog, I took the time to have a deep look into this. It is not a bug in DragSelect and has **nothing** to do with DragSelect.

# Explanation

I'll close it because it's not a bug in DragSelect, it's how Firefox is rendering the `<use>` output in combination with `x="" y=""` positions.

You can see that yourself when you inspect the elements with your browser (right-click on the SVG node and select "inspect"). Then you can see that Firefox, in contrary to Chrome, wrongly positions the element so that the selectable element is way bigger than what you actually see. Here are screenshots of this issue:

In Chrome:
<img width="1221" alt="Screen Shot 2021-08-22 at 08 56 27" src="https://user-images.githubusercontent.com/12467511/130346154-a58554eb-1994-40dc-ab76-278e843f63a8.png">

In Firefox:
<img width="1239" alt="Screen Shot 2021-08-22 at 08 55 52" src="https://user-images.githubusercontent.com/12467511/130346167-ef80db70-9e81-43a1-b002-8c549e3d1a5b.png">

You would have seen that yourself if you had inspected the elements and tried to debug yourself…

# Solution

So how can you solve it????? I found 2 possible solutions:
1. Don't use `<use xlink:href= …`. You can use the path element directly `<path transform=  …`. This will work.
2. Don't use `x="4727" y="1219"` to position your elements. You can use the `transform` property, like `transform="translate(4727,1219)"` instead.

Here is a working solution using the transform property: https://jsfiddle.net/c3792ga4/

# Notes
- I also had to change the `width`, `height` and `viewBox` properties)
- You don't need to handle css classes on selection yourself, you can just use `ds-selected`:

Don't do this:
```
.active { fill: red; }
ds.subscribe("callback", (current) => {
       prev = document.getElementsByClassName("active");
       Array.from(prev).forEach(el => el.classList.remove("active"));
       current.items.forEach(el => el.classList.add("active"))
     });
```

Do this instead:
```
.ds-selected { fill: red; }
```

**Closed by ThibaultJanBeyer** 2021-08-22 07:30 UTC
Labels: not an issue
