### ISSUE TITLE
Two consequent area selections mess up the area selection

### ISSUE THREAD

**Issue by joao-m-santos** [ThibaultJanBeyer/DragSelect#12] opened 2018-01-29 18:12 UTC
Hello,
This probably is a novice question or I must have messed something up myself, but nevertheless here's my issue:

When selecting an area by dragging over the target divs inside the designated area, everything works out fine, but if, after finishing this selection, I do the same, the area will get buggy and keep following my cursor until I click somewhere on the screen again. 

Any ideas how I can fix this?

PS: Is there a way to style the selection area?

**Comment by ThibaultJanBeyer** [comment] 2018-01-29 18:38
Hi @joao-m-santos thanks for sharing your issue and using the tool!

Unfortunately, I could not reproduce that issue locally. Would you be so kind to share your code. Or perhaps even better: share an example where your issue can be reproduced?
Feel free to fork any of the existing examples. For example this one: https://codepen.io/ThibaultJanBeyer/pen/Nvobgq

Otherwise, I won’t be able to help.

Regarding your second question, yes, it is definitively possible to style the selection area quite easily:

The tool adds [various classes](https://thibaultjanbeyer.github.io/DragSelect/#five) to the corresponding elements. In your case, you want to style `.ds-selector` with css. You can also turn off the automatically applied styles by settings `customStyles: true`. If set to true, no styles (except for position absolute) will be applied by default.

Don’t forget to have a look at the well maintained [documentation](https://thibaultjanbeyer.github.io/DragSelect/) for more information.

Greetings

**Comment by joao-m-santos** [comment] 2018-01-30 08:42
Hello @ThibaultJanBeyer and thank you for your quick response.
I tried reproducing my issue on your Codepen but I couldn't, so I recorded a small video exemplifying what I was talking about. You can view it at https://drive.google.com/open?id=159ga7s0oorL3D54LaZOV8do34f-m--py

My guess is I'm selecting the text inside the target divs and then it messes up the selector JS.

Thanks a lot for your attention and support

Best rgrds

**Comment by ThibaultJanBeyer** [comment] 2018-01-30 14:44
Hmm, it’s kind of impossible to tell what is going on with just a video…
So please do the following:

1. To check your assumption with the text inside the targets: try to add the CSS `user-select: none;` to the text inside your targets (just to see if that makes any difference). Maybe this solves your issue already.

2. Open your console and check if there are any javascript errors if you do your draggings. You can open your console in firefox via:  `Tools > Web Developer > Web Console` or in chrome via `View > Developer > JavaScript Console`. If there is something, write me what it says.

3. Give me more information:
- Which browser do you use?
- Which operating system?
- How did you implement DragSelect?
- Can you maybe also provide your code regarding that part HTML, JS, CSS?

In the video I also noted a weird thing: when you drag the second time, the cursor is in a `not-allowed` state. But no idea why.

I’ll again try to reproduce it on my side too…

**Comment by joao-m-santos** [comment] 2018-01-30 15:54
I applied your first fix and it worked. I'm guessing it was an issue of trying to drag the selected text, hence the `not-allowed` state.
I had no console errors whatsoever, I was using Chrome in Windows 10 and I implemented it like
`var ds = new DragSelect({options});`

Thanks for your help,
Best rgrds

**Comment by ThibaultJanBeyer** [comment] 2018-01-30 16:20
I’m glad that setting `user-select: none` helped in your case! 👍 

Does this solve your issue or do you want me to continue looking into it?

If so, please try to provide a code example where the issue can be reproduced because I did several tests on my side and could not reproduce it, even with selectable text inside of selectable elements. It did select the text but did not break the selection as in your video. So, I guess it’s something specific to your implementation. As long as I don’t have access to a code example that reproduces this issue there is not much I can do.

**Comment by ThibaultJanBeyer** [comment] 2018-02-04 16:09
So as it seems your issue is resolved. Closing it for now…

**Closed by ThibaultJanBeyer** 2018-02-04 16:09 UTC
