### ISSUE TITLE
Mobile view: selection and dragging is not working well

### ISSUE THREAD

**Issue by Xumochuan** [ThibaultJanBeyer/DragSelect#77] opened 2021-01-11 06:38 UTC
**Describe the bug**
Hi. thanks for the great lib!
In mobile view, selection and dragging is not working correctly. (a few times, it seems working). Please look at this video.
Also, when drag items, selection event is also triggered (only mobile view).
https://ttprivatenew.s3.amazonaws.com/pulse/mochuan-video/attachments/15715842/TinyTake11-01-2021-02-31-53.mp4

Looking forward to hearing from you.

Thanks

**To Reproduce**
1. Mobile view
2. Selection and dragging repeatly

**Screenshots**
![image](https://user-images.githubusercontent.com/47884397/104152809-98d6db80-541b-11eb-9122-b633774dca6e.png)

**Comment by ThibaultJanBeyer** [comment] 2021-01-12 16:52
Dear @Xumochuan, thanks a lot for using the tool!

I watched the video but I don't really see what is not working from the video. Could you please elaborate on that?
I was also not able to reproduce the selection being triggered on drag.

Can you please share more information? i.e. which device you are using and what do you mean by "not working correctly"?

**Comment by Xumochuan** [comment] 2021-01-12 17:20
Hi,
I checked it in your codepen example of Demo.
https://codepen.io/ThibaultJanBeyer/pen/prpwYG

Please play a bit in codepen
Thanks

**Comment by ThibaultJanBeyer** [comment] 2021-06-23 16:33
Would you be so kind to clarify:
- which device are you using?
- what is not working correctly? I tried but it did not draw the selection when dragging
- from your Video I really don't see what is wrong? It seems to be selected correctly
Would you mind creating a video with sound where you describe exactly what is not working? 
Thank you :)

**Comment by Xumochuan** [comment] 2021-06-23 16:43
Hi, @ThibaultJanBeyer 
My video is very simple to test.
I can't draw multi-items in mobile (iPhone safari).
Also, did you check your codepen example in mobile-responsive mode?

This is your codepen in git repo.
[https://codepen.io/ThibaultJanBeyer/pen/prpwYG](https://codepen.io/ThibaultJanBeyer/pen/prpwYG)
[https://prnt.sc/16guwjm](https://prnt.sc/16guwjm)

Thank you

**Comment by ThibaultJanBeyer** [comment] 2021-07-02 17:08
Dear @Xumochuan, yes I tried it:
- Tried it in chrome mobile mode
- Tried it in firefox mobile mode
- Tried it on my mobile phone
- Tried it with BrowserStack on iPhone safari

I could not see any issue in your video, nor your screenshot nor was I able to reproduce it in the devices above.
I'll, unfortunately, have to close this issue. We can reopen if you give me the exact steps that I can reproduce 1:1

**Closed by ThibaultJanBeyer** 2021-07-02 17:08 UTC
